# Generated by Django 5.2.9 on 2025-12-06 17:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='student_profile', serialize=False, to='accounts.user')),
                ('first_name', models.CharField(max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(max_length=150, verbose_name='last name')),
                ('middle_name', models.CharField(blank=True, max_length=150, verbose_name='middle name')),
                ('student_id', models.CharField(help_text='Unique ID for the student within the school.', max_length=20, unique=True, verbose_name='student ID')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1, verbose_name='gender')),
                ('date_of_birth', models.DateField(verbose_name='date of birth')),
                ('date_enrolled', models.DateField(auto_now_add=True, verbose_name='date enrolled')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether the student is currently enrolled.', verbose_name='active status')),
            ],
            options={
                'verbose_name': 'student',
                'verbose_name_plural': 'students',
                'ordering': ['last_name', 'first_name'],
            },
        ),
    ]
