# Generated by Django 5.2.9 on 2025-12-07 08:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0001_initial'),
        ('accounts', '0001_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='parent_profile', serialize=False, to='accounts.user')),
                ('title', models.CharField(blank=True, max_length=10)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100)),
                ('phone_number', models.CharField(max_length=15)),
                ('alternate_phone', models.CharField(blank=True, max_length=15)),
                ('relationship', models.CharField(choices=[('father', 'Father'), ('mother', 'Mother'), ('guardian', 'Guardian'), ('uncle', 'Uncle'), ('aunt', 'Aunt'), ('grandparent', 'Grandparent'), ('sibling', 'Sibling'), ('other', 'Other Relative')], max_length=15)),
                ('occupation', models.CharField(blank=True, max_length=100)),
                ('employer', models.CharField(blank=True, max_length=100)),
                ('work_phone', models.CharField(blank=True, max_length=15)),
                ('work_address', models.TextField(blank=True)),
                ('residential_address', models.TextField(blank=True)),
                ('hometown', models.CharField(blank=True, max_length=100)),
                ('region', models.CharField(blank=True, max_length=50)),
                ('is_primary_contact', models.BooleanField(default=False, help_text='Primary contact for school communications')),
                ('is_emergency_contact', models.BooleanField(default=False)),
                ('can_pickup_student', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'parents',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['last_name', 'first_name']},
        ),
        migrations.AddField(
            model_name='student',
            name='admission_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='admission_number',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='student',
            name='allergies',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='student',
            name='blood_group',
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AddField(
            model_name='student',
            name='current_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='academics.class'),
        ),
        migrations.AddField(
            model_name='student',
            name='ghana_card_number',
            field=models.CharField(blank=True, help_text='Ghana Card ID', max_length=20),
        ),
        migrations.AddField(
            model_name='student',
            name='hometown',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='student',
            name='house',
            field=models.CharField(blank=True, help_text='Boarding house name (if applicable)', max_length=50),
        ),
        migrations.AddField(
            model_name='student',
            name='index_number',
            field=models.CharField(blank=True, help_text='BECE/WASSCE Index Number', max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='student',
            name='medical_conditions',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='student',
            name='nationality',
            field=models.CharField(default='Ghanaian', max_length=50),
        ),
        migrations.AddField(
            model_name='student',
            name='previous_school',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='student',
            name='region',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='student',
            name='residential_address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='student',
            name='residential_status',
            field=models.CharField(choices=[('day', 'Day Student'), ('boarder', 'Boarder')], default='day', max_length=10),
        ),
        migrations.AddField(
            model_name='student',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='student',
            name='withdrawal_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='withdrawal_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='date_enrolled',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='date_of_birth',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='student',
            name='first_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1),
        ),
        migrations.AlterField(
            model_name='student',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='last_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='middle_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_id',
            field=models.CharField(db_index=True, max_length=20, unique=True),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['student_id'], name='students_student_1ff8ed_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['current_class', 'is_active'], name='students_current_5a1e34_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['admission_date'], name='students_admissi_f373b4_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['residential_status', 'is_active'], name='students_residen_5bef48_idx'),
        ),
        migrations.AlterModelTable(
            name='student',
            table='students',
        ),
        migrations.AddField(
            model_name='parent',
            name='students',
            field=models.ManyToManyField(related_name='parents', to='students.student'),
        ),
        migrations.AddIndex(
            model_name='parent',
            index=models.Index(fields=['is_primary_contact'], name='parents_is_prim_79bb33_idx'),
        ),
        migrations.AddIndex(
            model_name='parent',
            index=models.Index(fields=['relationship'], name='parents_relatio_c54322_idx'),
        ),
        migrations.AddIndex(
            model_name='parent',
            index=models.Index(fields=['is_emergency_contact'], name='parents_is_emer_677688_idx'),
        ),
    ]
