# Generated by Django 5.2.9 on 2025-12-10 17:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0006_gradelevel_is_final_level'),
        ('students', '0002_parent_alter_student_options_student_admission_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='graduation_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='graduation_year',
            field=models.ForeignKey(blank=True, help_text='Academic year when student graduated', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='graduated_students', to='academics.academicyear'),
        ),
        migrations.AddField(
            model_name='student',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('graduated', 'Graduated'), ('withdrawn', 'Withdrawn'), ('transferred', 'Transferred'), ('suspended', 'Suspended')], default='active', max_length=15),
        ),
    ]
