# Generated by Django 5.2.9 on 2025-12-10 12:29

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0005_remove_term_name'),
        ('students', '0002_parent_alter_student_options_student_admission_date_and_more'),
        ('teachers', '0002_add_subject_and_class_subject'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssessmentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('code', models.CharField(max_length=10, unique=True)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('weight', models.DecimalField(decimal_places=2, default=Decimal('1.00'), help_text='Weight in final grade calculation', max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'assessment_types',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='GradeScale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('is_default', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'grade_scales',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('max_score', models.DecimalField(decimal_places=2, default=Decimal('100.00'), max_digits=5)),
                ('weight', models.DecimalField(decimal_places=2, default=Decimal('1.00'), help_text='Weight of this assessment (overrides type weight if set)', max_digits=5)),
                ('date', models.DateField(blank=True, null=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('is_published', models.BooleanField(default=False, help_text='Students can see their grades when published')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('class_subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='academics.classsubject')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_assessments', to='teachers.teacher')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='academics.term')),
                ('assessment_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assessments', to='grades.assessmenttype')),
            ],
            options={
                'db_table': 'assessments',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('remarks', models.CharField(blank=True, max_length=255)),
                ('is_absent', models.BooleanField(default=False)),
                ('is_excused', models.BooleanField(default=False)),
                ('graded_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='grades.assessment')),
                ('graded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='graded_entries', to='teachers.teacher')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='students.student')),
            ],
            options={
                'db_table': 'grades',
                'ordering': ['student__last_name', 'student__first_name'],
            },
        ),
        migrations.CreateModel(
            name='GradeLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(max_length=5)),
                ('description', models.CharField(blank=True, max_length=50)),
                ('min_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('max_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('grade_point', models.DecimalField(decimal_places=2, default=0, help_text='Grade point value for GPA calculation', max_digits=3)),
                ('order', models.IntegerField(default=0)),
                ('scale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='levels', to='grades.gradescale')),
            ],
            options={
                'db_table': 'grade_scale_levels',
                'ordering': ['scale', '-min_score'],
            },
        ),
        migrations.CreateModel(
            name='TermResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_score', models.DecimalField(blank=True, decimal_places=2, help_text='Weighted score from class work, quizzes, assignments', max_digits=5, null=True)),
                ('exam_score', models.DecimalField(blank=True, decimal_places=2, help_text='Score from end of term examination', max_digits=5, null=True)),
                ('total_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('grade', models.CharField(blank=True, max_length=5)),
                ('grade_point', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('position', models.IntegerField(blank=True, null=True)),
                ('remarks', models.CharField(blank=True, max_length=255)),
                ('is_published', models.BooleanField(default=False)),
                ('calculated_at', models.DateTimeField(auto_now=True)),
                ('class_subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='term_results', to='academics.classsubject')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='term_results', to='students.student')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='term_results', to='academics.term')),
            ],
            options={
                'db_table': 'term_results',
                'ordering': ['term', 'class_subject__subject__name'],
            },
        ),
        migrations.AddIndex(
            model_name='assessment',
            index=models.Index(fields=['class_subject', 'term'], name='assessments_class_s_4594ed_idx'),
        ),
        migrations.AddIndex(
            model_name='assessment',
            index=models.Index(fields=['term', 'is_published'], name='assessments_term_id_2177af_idx'),
        ),
        migrations.AddIndex(
            model_name='grade',
            index=models.Index(fields=['assessment', 'student'], name='grades_assessm_b8af71_idx'),
        ),
        migrations.AddIndex(
            model_name='grade',
            index=models.Index(fields=['student', 'graded_at'], name='grades_student_b1dd45_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='grade',
            unique_together={('assessment', 'student')},
        ),
        migrations.AlterUniqueTogether(
            name='gradelevel',
            unique_together={('scale', 'grade')},
        ),
        migrations.AddIndex(
            model_name='termresult',
            index=models.Index(fields=['student', 'term'], name='term_result_student_662a48_idx'),
        ),
        migrations.AddIndex(
            model_name='termresult',
            index=models.Index(fields=['class_subject', 'term'], name='term_result_class_s_527cca_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='termresult',
            unique_together={('student', 'class_subject', 'term')},
        ),
    ]
