# Generated by Django 5.2.9 on 2025-12-10 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gradescale',
            options={'ordering': ['level_type', 'name']},
        ),
        migrations.AddField(
            model_name='assessmenttype',
            name='is_exam',
            field=models.BooleanField(default=False, help_text='Is this an examination (vs continuous assessment)?'),
        ),
        migrations.AddField(
            model_name='gradescale',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='gradescale',
            name='level_type',
            field=models.CharField(choices=[('primary', 'Primary School'), ('jhs', 'Junior High School'), ('shs', 'Senior High School'), ('all', 'All Levels')], default='all', help_text='Which school level this scale applies to', max_length=10),
        ),
    ]
