# Generated by Django 5.2.9 on 2025-12-09 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(blank=True, help_text='School logo (recommended size: 200x200px)', null=True, upload_to='school_logos/')),
                ('favicon', models.ImageField(blank=True, help_text='Browser favicon (recommended size: 32x32px)', null=True, upload_to='school_favicons/')),
                ('motto', models.CharField(blank=True, max_length=255)),
                ('address', models.TextField(blank=True)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('region', models.CharField(blank=True, max_length=100)),
                ('postal_code', models.CharField(blank=True, max_length=20)),
                ('country', models.CharField(default='Ghana', max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('alternate_phone', models.CharField(blank=True, max_length=20)),
                ('website', models.URLField(blank=True)),
                ('principal_name', models.CharField(blank=True, max_length=100)),
                ('founded_year', models.PositiveIntegerField(blank=True, null=True)),
                ('school_type', models.CharField(blank=True, choices=[('public', 'Public'), ('private', 'Private'), ('mission', 'Mission/Religious'), ('international', 'International')], max_length=20)),
                ('primary_color', models.CharField(default='#570DF8', help_text='Primary brand color (hex format, e.g., #570DF8)', max_length=7)),
                ('secondary_color', models.CharField(default='#F000B8', help_text='Secondary brand color (hex format)', max_length=7)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'School Settings',
                'verbose_name_plural': 'School Settings',
                'db_table': 'school_settings',
            },
        ),
    ]
