# Generated by Django 5.2.9 on 2025-12-09 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='force_password_change',
            field=models.BooleanField(default=False, help_text='Require user to change password on next login.', verbose_name='force password change'),
        ),
    ]
