# Generated by Django 5.2.9 on 2025-12-07 08:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='teacher_profile', serialize=False, to='accounts.user')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('staff_id', models.CharField(db_index=True, max_length=20, unique=True)),
                ('ghana_card_number', models.CharField(blank=True, help_text='Ghana Card ID', max_length=20)),
                ('ssnit_number', models.CharField(blank=True, max_length=20)),
                ('tin_number', models.CharField(blank=True, max_length=20)),
                ('employment_status', models.CharField(choices=[('full_time', 'Full Time'), ('part_time', 'Part Time'), ('contract', 'Contract'), ('volunteer', 'Volunteer')], default='full_time', max_length=15)),
                ('date_employed', models.DateField()),
                ('qualification', models.CharField(choices=[('diploma', 'Diploma'), ('bachelors', "Bachelor's Degree"), ('masters', "Master's Degree"), ('phd', 'PhD'), ('other', 'Other')], default='bachelors', max_length=20)),
                ('specialization', models.CharField(blank=True, help_text='Area of specialization (e.g., Mathematics, English)', max_length=100)),
                ('phone_number', models.CharField(blank=True, max_length=15)),
                ('emergency_contact_name', models.CharField(blank=True, max_length=100)),
                ('emergency_contact_phone', models.CharField(blank=True, max_length=15)),
                ('residential_address', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('termination_date', models.DateField(blank=True, null=True)),
                ('termination_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'teachers',
                'ordering': ['last_name', 'first_name'],
                'indexes': [models.Index(fields=['staff_id'], name='teachers_staff_i_fd641f_idx'), models.Index(fields=['is_active'], name='teachers_is_acti_d8ca50_idx'), models.Index(fields=['employment_status', 'is_active'], name='teachers_employm_09d3ad_idx')],
            },
        ),
    ]
