# Generated by Django 5.2.9 on 2025-12-07 08:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='class_teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_classes', to='teachers.teacher', verbose_name='Form Teacher/Class Teacher'),
        ),
        migrations.AlterUniqueTogether(
            name='gradelevel',
            unique_together={('level_type', 'numeric_level')},
        ),
        migrations.AddField(
            model_name='class',
            name='grade_level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='academics.gradelevel'),
        ),
        migrations.AddField(
            model_name='class',
            name='programme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='classes', to='academics.programme'),
        ),
        migrations.AddField(
            model_name='term',
            name='academic_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='terms', to='academics.academicyear'),
        ),
        migrations.AddIndex(
            model_name='class',
            index=models.Index(fields=['academic_year', 'is_active'], name='classes_academi_52eb73_idx'),
        ),
        migrations.AddIndex(
            model_name='class',
            index=models.Index(fields=['grade_level', 'is_active'], name='classes_grade_l_54ec9c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='class',
            unique_together={('grade_level', 'section', 'academic_year')},
        ),
        migrations.AlterUniqueTogether(
            name='term',
            unique_together={('academic_year', 'term_number')},
        ),
    ]
