# Generated by Django 5.2.9 on 2025-12-09 13:05

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_initial'),
        ('teachers', '0002_add_subject_and_class_subject'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('description', models.TextField(blank=True)),
                ('subject_type', models.CharField(choices=[('core', 'Core Subject'), ('elective', 'Elective Subject')], default='core', max_length=10)),
                ('credit_hours', models.DecimalField(decimal_places=1, default=1.0, help_text='Weight of subject in GPA calculation', max_digits=3)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('applicable_levels', models.ManyToManyField(blank=True, help_text='Grade levels where this subject is offered', related_name='available_subjects', to='academics.gradelevel')),
                ('programmes', models.ManyToManyField(blank=True, help_text='Programmes that offer this subject (for electives)', related_name='subjects', to='academics.programme')),
            ],
            options={
                'db_table': 'subjects',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ClassSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periods_per_week', models.IntegerField(default=4, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)])),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('class_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_subjects', to='academics.class')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subject_assignments', to='teachers.teacher')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_assignments', to='academics.subject')),
            ],
            options={
                'verbose_name': 'Class Subject Assignment',
                'verbose_name_plural': 'Class Subject Assignments',
                'db_table': 'class_subjects',
                'ordering': ['subject__name'],
            },
        ),
        migrations.AddIndex(
            model_name='subject',
            index=models.Index(fields=['subject_type', 'is_active'], name='subjects_subject_36e766_idx'),
        ),
        migrations.AddIndex(
            model_name='classsubject',
            index=models.Index(fields=['class_instance', 'is_active'], name='class_subje_class_i_1f738c_idx'),
        ),
        migrations.AddIndex(
            model_name='classsubject',
            index=models.Index(fields=['teacher', 'is_active'], name='class_subje_teacher_c3fb4c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='classsubject',
            unique_together={('class_instance', 'subject')},
        ),
    ]
