# Generated by Django 5.2.9 on 2025-12-09 21:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_add_subject_and_class_subject'),
        ('students', '0002_parent_alter_student_options_student_admission_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrollment_date', models.DateField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Class Enrollment',
                'verbose_name_plural': 'Class Enrollments',
                'db_table': 'class_enrollments',
                'ordering': ['-academic_year__start_date', 'class_instance__grade_level__order'],
            },
        ),
        migrations.RemoveIndex(
            model_name='class',
            name='classes_academi_52eb73_idx',
        ),
        migrations.AlterUniqueTogether(
            name='class',
            unique_together={('grade_level', 'section', 'programme')},
        ),
        migrations.AddField(
            model_name='classenrollment',
            name='academic_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='academics.academicyear'),
        ),
        migrations.AddField(
            model_name='classenrollment',
            name='class_instance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='academics.class'),
        ),
        migrations.AddField(
            model_name='classenrollment',
            name='promoted_from',
            field=models.ForeignKey(blank=True, help_text='Previous enrollment if student was promoted', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promoted_to', to='academics.classenrollment'),
        ),
        migrations.AddField(
            model_name='classenrollment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_enrollments', to='students.student'),
        ),
        migrations.RemoveField(
            model_name='class',
            name='academic_year',
        ),
        migrations.AddIndex(
            model_name='classenrollment',
            index=models.Index(fields=['academic_year', 'is_active'], name='class_enrol_academi_0f05c8_idx'),
        ),
        migrations.AddIndex(
            model_name='classenrollment',
            index=models.Index(fields=['class_instance', 'academic_year'], name='class_enrol_class_i_a58a88_idx'),
        ),
        migrations.AddIndex(
            model_name='classenrollment',
            index=models.Index(fields=['student', 'is_active'], name='class_enrol_student_23ef15_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='classenrollment',
            unique_together={('student', 'academic_year')},
        ),
    ]
