# Generated by Django 5.2.9 on 2025-12-09 22:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0004_classenrollment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='term',
            name='name',
        ),
    ]
