# Generated by Django 5.2.9 on 2025-12-10 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0005_remove_term_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='gradelevel',
            name='is_final_level',
            field=models.BooleanField(default=False, help_text='Mark as final level (e.g., Form 3, JHS 3). Students completing this level will graduate.'),
        ),
    ]
